# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Gaétan Zanella
# description: Explore the Fabernovel tech team’s latest musings on mobile development, front end, back end, modern architecture, Cloud, APIs and so much more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://gaetanzanella.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author:
  name: Gaétan Zanella
  url: "https://twitter.com/gaetanzanella"
  email: "gaetan.zanella@fabernovel.com"

# google_analytics: UA-455808-64

# Build settings
markdown: kramdown
include:
  - _pages

# Social
social_links:
  github: gaetanzanella
  twitter: gaetanzanella

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate: 10

collections:
  - apps

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
